### ISSUE TITLE
[JJM] Preparar Tutoriais

### ISSUE THREAD

**Issue by gavelino** [ES2-UFPI/2019-1#11]
Cada equipe deve preparar os tutoriais (How To) de como utilizar as tecnologias a serem adotadas p/ o desenvolvimento do projeto. 

Itens essenciais:
- Instalação e configuração do ambiente;
- Persistência de dados (exemplo prático);
- Uso de API (ex: api de tradução, mapas, calendar, etc);
- Requisições ao servidor (caso necessário p/ o projeto)

Obs: 
- Grupos que utilizarão a mesma tecnologia pode se organizar p/ apresentar em conjunto, possivelmente compondo duplas p/ cada tópico (um aluno de cada grupo);
- Projetos que utilizarem modelo cliente/servidor deverão desenvolver tutoriais p/ ambas as tecnlogias adotadas;
- Os tutoriais devem ser construídos na [wiki do repositório da disciplina](https://github.com/ES2-UFPI/2019-1/wiki) e adicionado links nas respectivas wikis dos projetos.
- As datas p/ apresentação dos tutorias será definida posteriormente.

**Comment by VictorCampelo** [comment]
Tutoriais Iniciados.
