### ISSUE TITLE
[404] Descrever Arquitetura da Solução na Wiki

### ISSUE THREAD

**Issue by gavelino** [ES2-UFPI/2019-1#12]
Definir a arquitetura a ser utilizada para o desenvolvimento da solução. Adicionar a descrição da arquitetura na Wiki do projeto. 

Material p/ referência disponível em https://docs.google.com/presentation/d/1WmkgmHK54Gh_wAEznkwPR5gV4l8DdlCdSRGrXPqcgbQ/edit?usp=sharing

**Comment by anapaulamendes** [comment]
Não consegui adicionar o @felipebarroscaminha . Felipe veja se você está no repositório da turma.

**Comment by anapaulamendes** [comment]
https://github.com/ES2-UFPI/gerenciamento-do-time-404/wiki#padr%C3%A3o-de-arquitetura
