### ISSUE TITLE
[404] Definir Plano de Iteração na Wiki

### ISSUE THREAD

**Issue by gavelino** [ES2-UFPI/2019-1#17]
Definir Plano de Iteração na Wiki. Exemplo: https://github.com/luiscarlossf/get-promo/wiki/Plano-de-Iteração

**Comment by anapaulamendes** [comment]
https://github.com/ES2-UFPI/gerenciamento-do-time-404/wiki/Plano-de-Itera%C3%A7%C3%B5es
