### ISSUE TITLE
[404] Criar Repositório GitHub 

### ISSUE THREAD

**Issue by gavelino** [ES2-UFPI/2019-1#2]
Opcionalmente mais de um repositório pode ser criado p/ módulos/subsistemas, porém um repositório principal p/ o projeto deve ser definido.

**Comment by anapaulamendes** [comment]
Feito! O nosso repositório para o gerenciamento do projeto é https://github.com/ES2-UFPI/gerenciamento-do-time-404
Descobrimos como colocar issues dos outros repositórios nele.
